name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: 3.5.4
    - name: install depts
      run: make install
    - name: Run a single line command
      run: make test_all
    - name: Hello
      run: echo Hello
